name: flutter_frontend
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  http: ^1.5.0



  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8
  smooth_page_indicator: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/google.png
    - assets/images/apple.png
    - assets/images/logo.png


